### ISSUE TITLE
Crash when opening Men's Form (w4)

### ISSUE THREAD

**Issue by wyattis** [human-nature-lab/trellis-app#449]
OOM crash

```
07-25 09:05:21.239  9431 30975 E AndroidRuntime: FATAL EXCEPTION: pool-3-thread-2
07-25 09:05:21.239  9431 30975 E AndroidRuntime: Process: edu.yale.trellis.surveyview, PID: 9431
07-25 09:05:21.239  9431 30975 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 75497480 byte allocation with 25165824 free bytes and 68MB until OOM, target footprint 154426824, growth limit 201326592
07-25 09:05:21.239  9431 30975 E AndroidRuntime: 	at java.util.Arrays.copyOf(Arrays.java:3257)
07-25 09:05:21.239  9431 30975 E AndroidRuntime: 	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
07-25 09:05:21.239  9431 30975 E AndroidRuntime: 	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649)
07-25 09:05:21.239  9431 30975 E AndroidRuntime: 	at java.lang.StringBuilder.append(StringBuilder.java:203)
07-25 09:05:21.239  9431 30975 E AndroidRuntime: 	at org.json.JSONStringer.string(JSONStringer.java:354)
07-25 09:05:21.239  9431 30975 E AndroidRuntime: 	at org.json.JSONStringer.key(JSONStringer.java:386)
07-25 09:05:21.239  9431 30975 E AndroidRuntime: 	at org.json.JSONObject.writeTo(JSONObject.java:734)
07-25 09:05:21.239  9431 30975 E AndroidRuntime: 	at org.json.JSONStringer.value(JSONStringer.java:246)
07-25 09:05:21.239  9431 30975 E AndroidRuntime: 	at org.json.JSONArray.writeTo(JSONArray.java:616)
07-25 09:05:21.239  9431 30975 E AndroidRuntime: 	at org.json.JSONStringer.value(JSONStringer.java:242)
07-25 09:05:21.239  9431 30975 E AndroidRuntime: 	at org.json.JSONObject.writeTo(JSONObject.java:734)
07-25 09:05:21.239  9431 30975 E AndroidRuntime: 	at org.json.JSONStringer.value(JSONStringer.java:246)
07-25 09:05:21.239  9431 30975 E AndroidRuntime: 	at org.json.JSONObject.writeTo(JSONObject.java:734)
07-25 09:05:21.239  9431 30975 E AndroidRuntime: 	at org.json.JSONStringer.value(JSONStringer.java:246)
07-25 09:05:21.239  9431 30975 E AndroidRuntime: 	at org.json.JSONArray.writeTo(JSONArray.java:616)
07-25 09:05:21.239  9431 30975 E AndroidRuntime: 	at org.json.JSONArray.toString(JSONArray.java:587)
07-25 09:05:21.239  9431 30975 E AndroidRuntime: 	at org.apache.cordova.PluginResult.<init>(PluginResult.java:49)
07-25 09:05:21.239  9431 30975 E AndroidRuntime: 	at org.apache.cordova.CallbackContext.success(CallbackContext.java:88)
07-25 09:05:21.239  9431 30975 E AndroidRuntime: 	at io.sqlc.SQLiteConnectorDatabase.executeSqlBatch(SQLiteConnectorDatabase.java:176)
07-25 09:05:21.239  9431 30975 E AndroidRuntime: 	at io.sqlc.SQLitePlugin$DBRunner.run(SQLitePlugin.java:341)
07-25 09:05:21.239  9431 30975 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-25 09:05:21.239  9431 30975 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-25 09:05:21.239  9431 30975 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
07-25 09:05:21.275   950 28104 D Debug   : low && ship && 3rd party app crash, so skip dump
07-25 09:05:21.276   950 28104 W ActivityManager: crash : edu.yale.trellis.surveyview,10272
07-25 09:05:21.289   950 28104 W ActivityTaskManager:   Force finishing activity edu.yale.trellis.surveyview/.MainActivity
07-25 09:05:21.292   950 28104 V WindowManager: Prepare app transition: transit=TRANSIT_CRASHING_ACTIVITY_CLOSE mNextAppTransition=TRANSIT_UNSET alwaysKeepCurrent=false displayId=0 Callers=com.android.server.wm.DisplayContent.prepareAppTransition:5809 com.android.server.wm.DisplayContent.prepareAppTransition:5803 com.android.server.wm.ActivityStack.finishTopCrashedActivityLocked:2733 com.android.server.wm.RootWindowContainer.finishTopCrashedActivities:2655 com.android.server.wm.ActivityTaskManagerService$LocalService.finishTopCrashedActivities:8921 
07-25 09:05:21.298   950 28104 V WindowManager: Changing focus from Window{25f94a1 u0 edu.yale.trellis.surveyview/edu.yale.trellis.surveyview.MainActivity} to null displayId=0 Callers=com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:567 com.android.server.wm.WindowManagerService.updateFocusedWindowLocked:6314 com.android.server.wm.DisplayContent.setFocusedApp:6775 com.android.server.wm.ActivityTaskManagerService.setResumedActivityUncheckLocked:6725 

```

**Comment by wyattis** [comment]
This query produced by TypeORM seems to be the issue:

```sql
SELECT "Form"."created_at" AS "Form_created_at", 
"Form"."updated_at" AS "Form_updated_at", 
"Form"."deleted_at" AS "Form_deleted_at", 
"Form"."id" AS "Form_id", 
"Form"."version" AS "Form_version", 
"Form"."is_published" AS "Form_is_published", 
"Form_skips"."deleted_at" AS "Form_skips_deleted_at", 
"Form_skips"."id" AS "Form_skips_id", 
"Form_skips"."show_hide" AS "Form_skips_show_hide", 
"Form_skips"."any_all" AS "Form_skips_any_all", 
"Form_skips"."precedence" AS "Form_skips_precedence", 
"Form_skips"."custom_logic" AS "Form_skips_custom_logic", 
"Form_skips_conditionTags"."deleted_at" AS "Form_skips_conditionTags_deleted_at", 
"Form_skips_conditionTags"."id" AS "Form_skips_conditionTags_id", 
"Form_skips_conditionTags"."skip_id" AS "Form_skips_conditionTags_skip_id", 
"Form_skips_conditionTags"."condition_tag_name" AS "Form_skips_conditionTags_condition_tag_name", 
"Form_nameTranslation"."deleted_at" AS "Form_nameTranslation_deleted_at", 
"Form_nameTranslation"."id" AS "Form_nameTranslation_id", 
"Form_sections"."deleted_at" AS "Form_sections_deleted_at", 
"Form_sections"."id" AS "Form_sections_id", 
"Form_sections"."name_translation_id" AS "Form_sections_name_translation_id", 
"Form_sections_nameTranslation"."deleted_at" AS "Form_sections_nameTranslation_deleted_at", 
"Form_sections_nameTranslation"."id" AS "Form_sections_nameTranslation_id", 
"Form_sections_questionGroups"."deleted_at" AS "Form_sections_questionGroups_deleted_at", 
"Form_sections_questionGroups"."id" AS "Form_sections_questionGroups_id", 
"Form_sections_questionGroups_sectionQuestionGroup"."deleted_at" AS "Form_sections_questionGroups_sectionQuestionGroup_deleted_at", 
"Form_sections_questionGroups_sectionQuestionGroup"."id" AS "Form_sections_questionGroups_sectionQuestionGroup_id", 
"Form_sections_questionGroups_sectionQuestionGroup"."question_group_order" AS "Form_sections_questionGroups_sectionQuestionGroup_question_group_order", 
"Form_sections_questionGroups_skips"."deleted_at" AS "Form_sections_questionGroups_skips_deleted_at", 
"Form_sections_questionGroups_skips"."id" AS "Form_sections_questionGroups_skips_id", 
"Form_sections_questionGroups_skips"."show_hide" AS "Form_sections_questionGroups_skips_show_hide", 
"Form_sections_questionGroups_skips"."any_all" AS "Form_sections_questionGroups_skips_any_all", 
"Form_sections_questionGroups_skips"."precedence" AS "Form_sections_questionGroups_skips_precedence", 
"Form_sections_questionGroups_skips"."custom_logic" AS "Form_sections_questionGroups_skips_custom_logic", 
"Form_sections_questionGroups_skips_conditionTags"."deleted_at" AS "Form_sections_questionGroups_skips_conditionTags_deleted_at", 
"Form_sections_questionGroups_skips_conditionTags"."id" AS "Form_sections_questionGroups_skips_conditionTags_id", 
"Form_sections_questionGroups_skips_conditionTags"."skip_id" AS "Form_sections_questionGroups_skips_conditionTags_skip_id", 
"Form_sections_questionGroups_skips_conditionTags"."condition_tag_name" AS "Form_sections_questionGroups_skips_conditionTags_condition_tag_name", 
"Form_sections_formSections"."deleted_at" AS "Form_sections_formSections_deleted_at", 
"Form_sections_formSections"."id" AS "Form_sections_formSections_id", 
"Form_sections_formSections"."form_id" AS "Form_sections_formSections_form_id", 
"Form_sections_formSections"."sort_order" AS "Form_sections_formSections_sort_order", 
"Form_sections_formSections"."is_repeatable" AS "Form_sections_formSections_is_repeatable", 
"Form_sections_formSections"."max_repetitions" AS "Form_sections_formSections_max_repetitions", 
"Form_sections_formSections"."repeat_prompt_translation_id" AS "Form_sections_formSections_repeat_prompt_translation_id", 
"Form_sections_formSections"."follow_up_question_id" AS "Form_sections_formSections_follow_up_question_id", 
"Form_sections_formSections"."randomize_follow_up" AS "Form_sections_formSections_randomize_follow_up" 
FROM "form" "Form" 
LEFT JOIN "form_skip" "Form_Form_skips" ON "Form_Form_skips"."form_id"="Form"."id" 
LEFT JOIN "skip" "Form_skips" ON "Form_skips"."id"="Form_Form_skips"."skip_id"  
LEFT JOIN "skip_condition_tag" "Form_skips_conditionTags" ON "Form_skips_conditionTags"."skip_id"="Form_skips"."id"  
LEFT JOIN "translation" "Form_nameTranslation" ON "Form_nameTranslation"."id"="Form"."name_translation_id"  
LEFT JOIN "form_section" "Form_Form_sections" ON "Form_Form_sections"."form_id"="Form"."id" 
LEFT JOIN "section" "Form_sections" ON "Form_sections"."id"="Form_Form_sections"."section_id"  
LEFT JOIN "translation" "Form_sections_nameTranslation" ON "Form_sections_nameTranslation"."id"="Form_sections"."name_translation_id"  
LEFT JOIN "section_question_group" "Form_sections_Form_sections_questionGroups" ON "Form_sections_Form_sections_questionGroups"."section_id"="Form_sections"."id" 
LEFT JOIN "question_group" "Form_sections_questionGroups" ON "Form_sections_questionGroups"."id"="Form_sections_Form_sections_questionGroups"."question_group_id"  
LEFT JOIN "section_question_group" "Form_sections_questionGroups_sectionQuestionGroup" ON "Form_sections_questionGroups_sectionQuestionGroup"."question_group_id"="Form_sections_questionGroups"."id"  
LEFT JOIN "question_group_skip" "Form_sections_questionGroups_Form_sections_questionGroups_skips" ON "Form_sections_questionGroups_Form_sections_questionGroups_skips"."question_group_id"="Form_sections_questionGroups"."id" 
LEFT JOIN "skip" "Form_sections_questionGroups_skips" ON "Form_sections_questionGroups_skips"."id"="Form_sections_questionGroups_Form_sections_questionGroups_skips"."skip_id"  
LEFT JOIN "skip_condition_tag" "Form_sections_questionGroups_skips_conditionTags" ON "Form_sections_questionGroups_skips_conditionTags"."skip_id"="Form_sections_questionGroups_skips"."id"  
LEFT JOIN "form_section" "Form_sections_formSections" ON "Form_sections_formSections"."section_id"="Form_sections"."id" 
WHERE "Form"."id" = "9a09a4da-592b-462e-95fc-fc2301cf6d98" -- PARAMETERS: ["9a09a4da-592b-462e-95fc-fc2301cf6d98"]
```
